# Generated by Django 4.2.13 on 2024-06-21 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_post_category_alter_post_banner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('NAT', 'Nature'), ('TECH', 'Technology'), ('LIFE', 'Lifestyle'), ('FIN', 'Finance'), ('EDU', 'Education'), ('ENT', 'Entertainment'), ('HEAL', 'Health'), ('FOOD', 'Food & Drink'), ('TRVL', 'Travel'), ('SPT', 'Sports'), ('BUS', 'Business'), ('SCI', 'Science'), ('POL', 'Politics'), ('ART', 'Art & Culture'), ('MUS', 'Music'), ('MOV', 'Movies & TV'), ('AUTO', 'Automotive'), ('DIY', 'DIY & Crafts'), ('FASH', 'Fashion'), ('GAM', 'Gaming'), ('PETS', 'Pets'), ('PHOT', 'Photography'), ('HOME', 'Home & Garden'), ('REL', 'Religion & Spirituality'), ('OTR', 'Other')], default='OTR', max_length=4),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
